### ISSUE TITLE
Issue warning when permissions are wrong

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#120]
**Describe the solution you'd like**

When `safe_remove_reaction` fails due to permissions issues we can issue a warning in the channel to let the server admins know that the bot has incorrect permissions so they can potentially take action to resolve the issue.

We should also add a way to silence this warning so that admins who don't want to give SpellBot those permissions can make this warning go away.

**Comment by lexicalunit** [comment]
```
2020-07-31T00:11:15.748771+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-07-31T00:11:15.748772+00:00 app[worker.1]: 
2020-07-31T00:11:15.748772+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-31T00:11:15.748772+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
2020-07-31T00:11:15.748773+00:00 app[worker.1]:     msg = self.format(record)
2020-07-31T00:11:15.748773+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
2020-07-31T00:11:15.748773+00:00 app[worker.1]:     return fmt.format(record)
2020-07-31T00:11:15.748774+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
2020-07-31T00:11:15.748774+00:00 app[worker.1]:     record.message = record.getMessage()
2020-07-31T00:11:15.748774+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
2020-07-31T00:11:15.748775+00:00 app[worker.1]:     msg = msg % self.args
2020-07-31T00:11:15.748775+00:00 app[worker.1]: TypeError: not all arguments converted during string formatting
2020-07-31T00:11:15.748775+00:00 app[worker.1]: Call stack:
2020-07-31T00:11:15.748776+00:00 app[worker.1]:   File "/usr/local/bin/spellbot", line 8, in <module>
2020-07-31T00:11:15.748776+00:00 app[worker.1]:     sys.exit(main())
2020-07-31T00:11:15.748776+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-07-31T00:11:15.748777+00:00 app[worker.1]:     return self.main(*args, **kwargs)
2020-07-31T00:11:15.748777+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-07-31T00:11:15.748778+00:00 app[worker.1]:     rv = self.invoke(ctx)
2020-07-31T00:11:15.748778+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-07-31T00:11:15.748778+00:00 app[worker.1]:     return ctx.invoke(self.callback, **ctx.params)
2020-07-31T00:11:15.748779+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-07-31T00:11:15.748779+00:00 app[worker.1]:     return callback(*args, **kwargs)
2020-07-31T00:11:15.748779+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/spellbot/__init__.py", line 1987, in main
2020-07-31T00:11:15.748780+00:00 app[worker.1]:     client.run()
2020-07-31T00:11:15.748780+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/spellbot/__init__.py", line 458, in run
2020-07-31T00:11:15.748780+00:00 app[worker.1]:     super().run(self.token)
2020-07-31T00:11:15.748781+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 631, in run
2020-07-31T00:11:15.748781+00:00 app[worker.1]:     loop.run_forever()
2020-07-31T00:11:15.748781+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
2020-07-31T00:11:15.748782+00:00 app[worker.1]:     self._run_once()
2020-07-31T00:11:15.748782+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
2020-07-31T00:11:15.748783+00:00 app[worker.1]:     handle._run()
2020-07-31T00:11:15.748783+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
2020-07-31T00:11:15.748783+00:00 app[worker.1]:     self._context.run(self._callback, *self._args)
2020-07-31T00:11:15.748784+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
2020-07-31T00:11:15.748784+00:00 app[worker.1]:     await coro(*args, **kwargs)
2020-07-31T00:11:15.748785+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/spellbot/__init__.py", line 686, in on_raw_reaction_add
2020-07-31T00:11:15.748785+00:00 app[worker.1]:     await self.safe_remove_reaction(message, emoji, author)
2020-07-31T00:11:15.748785+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/spellbot/__init__.py", line 357, in safe_remove_reaction
2020-07-31T00:11:15.748786+00:00 app[worker.1]:     logger.exception("warning: discord: could not remove reaction", e)
2020-07-31T00:11:15.748786+00:00 app[worker.1]: Message: 'warning: discord: could not remove reaction'
2020-07-31T00:11:15.748786+00:00 app[worker.1]: Arguments: (Forbidden('403 Forbidden (error code: 50013): Missing Permissions'),)
```

**Comment by lexicalunit** [comment]
The issue warnings part is completed thanks to @crookedneighbor via https://github.com/lexicalunit/spellbot/pull/143 🎉
