### ISSUE TITLE
Handle Invalid Form Body

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#456]
```
[2021-04-30 20:15:43][spellbot.operations][ERROR] - warning: discord: could not send message to channel: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spellbot/operations.py", line 361, in safe_send_channel
    return await messageable.send(content, embed=embed, file=file)
  File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1064, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
```

**Comment by lexicalunit** [comment]
Duplicate of https://github.com/lexicalunit/spellbot/issues/384
