### ISSUE TITLE
asyncio error: Task exception was never retrieved

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#487]
Got this today.

```
2021-05-12T04:04:09.696866+00:00 app[web.1]: [2021-05-12 04:04:09][asyncio][ERROR] - Task exception was never retrieved
2021-05-12T04:04:09.696885+00:00 app[web.1]: future: <Task finished name='Task-15' coro=<ConnectionState._delay_ready() done, defined at /usr/local/lib/python3.9/site-packages/discord/state.py:406> exception=ConnectionResetError('Cannot write to closing transport')>
2021-05-12T04:04:09.696886+00:00 app[web.1]: Traceback (most recent call last):
2021-05-12T04:04:09.696887+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 420, in _delay_ready
2021-05-12T04:04:09.696887+00:00 app[web.1]:     future = await self.chunk_guild(guild, wait=False)
2021-05-12T04:04:09.696888+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 838, in chunk_guild
2021-05-12T04:04:09.696888+00:00 app[web.1]:     await self.chunker(guild.id, nonce=request.nonce)
2021-05-12T04:04:09.696888+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 387, in chunker
2021-05-12T04:04:09.696889+00:00 app[web.1]:     await ws.request_chunks(guild_id, query=query, limit=limit, presences=presences, nonce=nonce)
2021-05-12T04:04:09.696890+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 654, in request_chunks
2021-05-12T04:04:09.696890+00:00 app[web.1]:     await self.send_as_json(payload)
2021-05-12T04:04:09.696891+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 591, in send_as_json
2021-05-12T04:04:09.696891+00:00 app[web.1]:     await self.send(utils.to_json(data))
2021-05-12T04:04:09.696892+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 587, in send
2021-05-12T04:04:09.696892+00:00 app[web.1]:     await self.socket.send_str(data)
2021-05-12T04:04:09.696892+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
2021-05-12T04:04:09.696893+00:00 app[web.1]:     await self._writer.send(data, binary=False, compress=compress)
2021-05-12T04:04:09.696893+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
2021-05-12T04:04:09.696893+00:00 app[web.1]:     await self._send_frame(message, WSMsgType.TEXT, compress)
2021-05-12T04:04:09.696894+00:00 app[web.1]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
2021-05-12T04:04:09.696894+00:00 app[web.1]:     raise ConnectionResetError("Cannot write to closing transport")
2021-05-12T04:04:09.696895+00:00 app[web.1]: ConnectionResetError: Cannot write to closing transport
```

**Comment by lexicalunit** [comment]
Should be resolved by move to slash commands and `@task` for background processing.
